# Generated by Django 5.2.12 on 2026-06-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='csv_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
